[[sec-test-new]]
= Test developer guide: New Tests

== Test requirements

A reference implementation cannot be accepted without a valid test specification. See link:./DEFINERS.adoc[Test definers guide] for information in how to submit for review a new test specification. The test specification will be used to validate and review the reference implementation. 


== Specify test input parameters

Input parameters of the test are included in a `yaml` file named `config.yaml`. This file lives in the same directory as the test specification and reference implementation. They can be used for instance to establish a meaningful window interval of measurement given a dataset or to define the requirements of the T-GM class specification to comply. See the following example of a test input parameter specification for a test located in link:https://github.com/redhat-partner-solutions/vse-sync-test/blob/main/tests/sync/G.8272/time-error-in-locked-mode/DPLL-to-PHC/PRTC-A/config.yaml[config.yaml].

== Manage dependencies

We use git submodules to manage the dependencies this repo has on other repos we have developed. During development stage, you want to just go grab the latest version of every dependent submodule. To pull the latest changes present in link:https://github.com/redhat-partner-solutions/vse-sync-pp[vse-sync-pp]:

[source,console]
$ git submodule update --init --recursive

== Write the new test

This is of primal importance to get your PR reviewed. When creating a new test reference implementation that can be submitted for review, you first need to ensure that the required  submodules used to implement your test reference implementation are already available in your repo. Second, you need to ensure the leveraged dependencies have meaningful unit tests and those unit tests are passing. Without these two requirements, your PR submitting a new test cannot be accepted for review.

A recommended template for getting started developing your test reference implementation can be found in link:https://github.com/redhat-partner-solutions/vse-sync-test/blob/main/tests/sync/G.8272/time-error-in-locked-mode/DPLL-to-PHC/PRTC-A/testimpl.py[testimpl.py].

== Add data to execute the new test
 
In order for a reviewer to accept a submission of a new test reference implementation, you need to include in your submission sample data files which will prove to a reviewer that your submitted test reference implementation actually works. Data inputs to run a test can come from the logs of the linux-ptp-daemon or from the collectors in link:https://github.com/redhat-partner-solutions/vse-sync-collection-tools[vse-sync-collection-tools]. In this way, the reference implementation must always include a parser that is compliant with the logs gathered from the PTP operator or the logs gathered from the collector.

For properly demultiplexing input data coming from all the collectors developed in link:https://github.com/redhat-partner-solutions/vse-sync-collection-tools[vse-sync-collection-tools], you can leverage the `vse_sync_pp.demux` module developed in link:https://github.com/redhat-partner-solutions/vse-sync-pp[vse-sync-pp]. See more information about `vse_sync_pp.demux` module usage in the user documentation provided in link:https://github.com/redhat-partner-solutions/vse-sync-pp/blob/main/README.md[vse-sync-pp].

== Execute the new test

To execute the reference implementation with the test input parameters, you need to include data sets that provide both a pass and fail test associated to a test reference implementation. Note that a PR cannot be accepted without including sample data set to validate the test reference implementation. 
In what follows see two examples that assume you are under the following directory path `tests/sync/G.8272/time-error-in-locked-mode/1PPS-to-DPLL/PRTC-A` of this repo. See the following example of a test that passes located in `sync/G.8272/time-error-in-locked-mode/1PPS-to-DPLL/PRTC-A`:

[source,console]
$ PPATH=../../../../../../vse-sync-pp/src
$ PYTHONPATH=$PPATH python3 testimpl.py  ../examples/dpll-PRTCA-accept.dat
{"result": true, "reason": null, "analysis": {"duration": 2458.27, "terror": {"units": "ns", "min": -5.14, "max": 5.58, "range": 10.72, "mean": -0.001, "stddev": 2.453, "variance": 6.016}}}

See the following test execution from the same test in `sync/G.8272/time-error-in-locked-mode/1PPS-to-DPLL/PRTC-A` but with different data revealing a result showing the test did not pass:

[source,console]
$ PPATH=../../../../../../vse-sync-pp/src
$ PYTHONPATH=$PPATH python3 testimpl.py  ../examples/dpll-reject.dat
{"result": false, "reason": "short test duration", "analysis": {"duration": 475.7922967, "terror": {"units": "ns", "min": -3.49, "max": 5.84, "range": 9.33, "mean": 0.03, "stddev": 2.342, "variance": 5.486}}}

== Publish your test

All the developed test reference implementations are only considered to be valid when the repo is published and the test lives in the main branch of this repo. A test that has made it to the `main` branch has its `test id` permanently allocated and is closed for modifications. To get your developed test considered for reviewed and eventually get published in the `main` branch of this repo you must submit a PR following these basic principles:

* The PR must include, if not already present in the main branch, the test specification is intending to develop. The PR will be closed if there is no test specification for that test reference implementation in the main branch or included in the PR.

* The provided test reference implementation in the PR leverages submodules in link:https://github.com/redhat-partner-solutions/vse-sync-pp[vse-sync-pp]. Unit tests for all those modules must pass before even starting to consider the PR submitted for review.

* For the PR to be considered for review, a test reference implementation must provide a yaml file within the same folder specifying test input parameters for the test reference implementation.

* The contributors must explicitly indicate in their PR, if a new test is still work in progress, and post an update, once the status of the pull request changes, otherwise maintainers of the repo will assume the submission is ready for review, while it actually is not.

* If the PR is still ongoing, but the contributor no longer wants to continue, then this should be communicated, so that someone else can pick it up or the PR will be closed.

* Any submitted PR must be kept conflict free and rebased within reasonable time.

[[sec-test-modified]]
= Test Developer Guide: Modified tests

Note that changes to an already published test cannot be accepted because a public test identifier must always mean the same thing. The previous statement applies both to any change to a test specification procedure and a test reference implementation. Therefore, the procedure to update an already published test requires the creation of a new test with a new test identifier, a new test specification, and a new test reference implementation. 

* To submit for review a test specification follow link:./DEFINERS.adoc[Test definers guide] for information in how to submit for review a new test specification.

* To submit for review a test reference implementation follow <<sec-test-new>>.
  
